"use client";
import { ScoreResult } from "./score-result";
import { useMemo, useState } from "react";
import { ArrowRight, Check, RotateCcw } from "lucide-react";
import { inverseNormal, normalCdf } from "@/lib/stats";
import { NormalCurve } from "./normal-curve";
import { useProgress } from "./progress-provider";

type Q={type:"z"|"area"|"value"|"drag";prompt:string;answer:number;mu:number;sd:number;lower?:number;upper?:number};
function makeQuestions():Q[]{return Array.from({length:10},(_,i)=>{const mu=[50,72,100,420][i%4],sd=[6,8,15,35][i%4];if(i%4===0){const x=mu+sd*(i%3-1);return{type:"z",prompt:`A Normal variable has μ=${mu} and σ=${sd}. What is the z-score of x=${x}?`,answer:(x-mu)/sd,mu,sd};}if(i%4===1){const z=-1.5+(i%5)*.5;return{type:"area",prompt:`What percent of a standard Normal distribution is below z=${z.toFixed(1)}?`,answer:normalCdf(z)*100,mu:0,sd:1,upper:z};}if(i%4===2){const pct=[.1,.25,.75,.9][i%4],z=inverseNormal(pct);return{type:"value",prompt:`A Normal variable has μ=${mu} and σ=${sd}. Find the value with ${(pct*100).toFixed(0)}% below it.`,answer:mu+z*sd,mu,sd};}const lo=-1-(i%2)*.5,hi=1+(i%2)*.5;return{type:"drag",prompt:`Drag the bounds to shade the region from z=${lo.toFixed(1)} to z=${hi.toFixed(1)}.`,answer:normalCdf(hi)-normalCdf(lo),mu:0,sd:1,lower:lo,upper:hi};});}

export function NormalQuiz(){const questions=useMemo(()=>makeQuestions(),[]),{recordActivity}=useProgress();const[i,setI]=useState(0),[value,setValue]=useState(""),[lo,setLo]=useState(-1),[hi,setHi]=useState(1),[feedback,setFeedback]=useState<boolean|null>(null),[score,setScore]=useState(0),[done,setDone]=useState(false);const q=questions[i];
  function check(){if(feedback!==null)return;const ok=q.type==="drag"?Math.abs(lo-(q.lower??0))<.06&&Math.abs(hi-(q.upper??0))<.06:Boolean(value.trim())&&Math.abs(Number(value)-q.answer)<(q.type==="area"?.12:.06);setFeedback(ok);if(ok)setScore(score+1);}
  function next(){if(i===questions.length-1){setDone(true);void recordActivity("Normal Curve Quiz",score,questions.length);}else{setI(i+1);setValue("");setFeedback(null);const n=questions[i+1];setLo(n.lower??-1);setHi(n.upper??1);}}
  if(done)return <main className="activity-page wrap"><section className="result-card"><div className="result-ring"><strong>{score}/10</strong><span>correct</span></div><div><span className="kicker">Normal curve quiz</span><h1>{score>=8?"You can see the curve.":"One more round will sharpen it."}</h1><p>Areas, z-scores, percentiles, and draggable bounds—all in one set.</p><button className="button button-accent" onClick={()=>{setI(0);setValue("");setLo(-1);setHi(1);setScore(0);setDone(false);setFeedback(null);}}>Try again <RotateCcw size={17}/></button></div></section><ScoreResult activity="Normal Curve Quiz"/></main>;
  const displayLo=q.type==="area"?-3.5:q.type==="drag"?lo:-1,displayHi=q.type==="area"?(q.upper??0):q.type==="drag"?hi:1;
  return <main className="activity-page wrap narrow"><div className="activity-heading compact"><div><span className="kicker">Quiz / normal distributions</span><h1>Read the curve.</h1></div><div className="score-pill">{score} correct · {i+1}/10</div></div><div className="progress-track"><span style={{width:`${i*10}%`}}/></div><section className="normal-quiz-card"><div className="question-number">Question {i+1}</div><h2>{q.prompt}</h2><NormalCurve lower={displayLo} upper={displayHi} interactive={q.type==="drag"} onLower={setLo} onUpper={setHi}/>{q.type!=="drag"&&<label className="single-answer">Your answer {q.type==="area"&&<span>(percent)</span>}<input value={value} onChange={e=>setValue(e.target.value)} inputMode="decimal" placeholder="0.00" disabled={feedback!==null}/></label>}{feedback===null?<button className="button button-dark" onClick={check} disabled={q.type!=="drag"&&!value}>Check answer</button>:<div className={feedback?"answer-feedback correct":"answer-feedback incorrect"}><div><Check/><strong>{feedback?"Correct.":q.type==="drag"?`Set the handles to ${q.lower?.toFixed(1)} and ${q.upper?.toFixed(1)}.`:`Answer: ${q.answer.toFixed(2)}${q.type==="area"?"%":""}`}</strong></div><button className="button button-accent" onClick={next}>Next <ArrowRight size={17}/></button></div>}</section></main>;
}
