"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Pause, Play, RotateCcw } from "lucide-react";
import { normalCdf } from "@/lib/stats";
import { NormalCurve } from "./normal-curve";
import { useProgress } from "./progress-provider";

const finalBins=[1,5,16,36,62,88,112,124,112,88,62,36,16,5,1];
export function NormalLesson(){const[count,setCount]=useState(0),[running,setRunning]=useState(false),[lower,setLower]=useState(-1),[upper,setUpper]=useState(1);const{completeUnit}=useProgress();
  useEffect(()=>{if(!running)return;const timer=window.setInterval(()=>setCount(c=>{if(c>=600){setRunning(false);return 600;}return c+4;}),28);return()=>window.clearInterval(timer);},[running]);
  const bins=useMemo(()=>finalBins.map((v,i)=>Math.round(v*count/600)+((count+i*7)%19===0?1:0)),[count]);
  const area=normalCdf(upper)-normalCdf(lower);
  return <main className="lesson-page"><section className="lesson-intro wrap"><span className="kicker">Interactive lesson · 8 minutes</span><h1>Why does the normal curve keep appearing?</h1><p>It begins when many small, independent chances add together. Build the shape, then measure it.</p><div className="lesson-progress"><span className={count>0?"done":""}>1</span><i/><span className={count>=600?"done":""}>2</span><i/><span>3</span></div></section>
  <section className="lesson-block plinko-section"><div className="wrap lesson-grid"><div><span className="step-number">01</span><h2>Let randomness pile up.</h2><p>At each peg, a ball is equally likely to fall left or right. Most paths contain a mix of left and right turns, so balls collect near the center. All-left or all-right paths are rare.</p><div className="lesson-note"><strong>The hidden math</strong><span>Each landing position follows a binomial distribution. With enough rows, its outline approaches a normal curve.</span></div></div><div className="plinko-card"><div className="plinko-top"><span>{count} balls dropped</span><div><button aria-label="Reset" onClick={()=>{setCount(0);setRunning(false);}}><RotateCcw/></button><button className="play" onClick={()=>setRunning(!running)}>{running?<Pause/>:<Play/>}{running?"Pause":count?"Continue":"Drop balls"}</button></div></div><div className="plinko-board" aria-label="Animated Plinko board forming a bell-shaped histogram"><div className="pegs">{Array.from({length:9},(_,row)=><div key={row}>{Array.from({length:row+4},(_,i)=><i key={i}/>)}</div>)}</div>{running&&<b className="falling-ball" key={count} style={{left:`${46+(count%9-4)*2}%`}}/>}<div className="histogram">{bins.map((height,i)=><span key={i} style={{height:`${Math.min(100,height)}%`}}/>)}</div></div><button className="plinko-skip" onClick={()=>{setCount(600);setRunning(false);}}>Fill all 600</button></div></div></section>
  <section className="lesson-block curve-section"><div className="wrap lesson-grid reverse"><div className="curve-lesson-card"><NormalCurve lower={lower} upper={upper} interactive onLower={setLower} onUpper={setUpper}/><div className="equation-card"><span>Standardize</span><strong>z = (x − μ) / σ</strong><span>Area</span><strong>P({lower.toFixed(1)} &lt; Z &lt; {upper.toFixed(1)}) = {(area).toFixed(4)}</strong></div></div><div><span className="step-number">02</span><h2>Area is probability.</h2><p>The total area under a density curve is 1. Choose two z-score bounds; the shaded area is the proportion of observations expected between them.</p><ul className="rule-list"><li><strong>68%</strong><span>within 1 standard deviation</span></li><li><strong>95%</strong><span>within 2 standard deviations</span></li><li><strong>99.7%</strong><span>within 3 standard deviations</span></li></ul></div></div></section>
  <section className="lesson-finish wrap"><div><span className="step-number">03</span><h2>Turn the picture into a skill.</h2><p>Practice moving between raw values, z-scores, and areas. The graph stays beside you.</p></div><Link className="button button-accent" href="/normal/quiz" onClick={()=>void completeUnit("normal-curves")}>Practice normal curves <ArrowRight size={18}/></Link></section></main>;
}
