"use client";

import { useRef, useState } from "react";
import data from "@/lib/question-bank.json";

const families = ['One-proportion z test','Two-proportion z test','One-sample t test','Two-sample t test','Paired t test','Chi-square goodness-of-fit','Chi-square independence','Chi-square homogeneity','Regression slope t test'];
const skills = { identify: 'Choose the correct test', ci: 'Calculate a confidence interval', pvalue: 'Calculate a p-value', alpha: 'Compare p with α & decide' };
type Skill = keyof typeof skills;
type Question = { id:string; family:number; skill:string; prompt:string; options:string[]; answer:(string|number)[]; explanation:string };
function shuffle<T,>(items:T[]) { const a=[...items]; for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];} return a; }
export default function QuizBuilder() {
 const [tests,setTests]=useState(families.map((_,i)=>i));
 const [topics,setTopics]=useState<Skill[]>(Object.keys(skills) as Skill[]);
 const [mode,setMode]=useState('round'); const [count,setCount]=useState('10');
 const [deck,setDeck]=useState<Question[]>([]); const [index,setIndex]=useState(0);
 const [answers,setAnswers]=useState<{question:Question; correct:boolean; response:string}[]>([]);
 const [values,setValues]=useState(['','']); const [submitted,setSubmitted]=useState(false);
 const [done,setDone]=useState(false); const [error,setError]=useState('');
 const heading=useRef<HTMLHeadingElement>(null);
 const pool=data.filter(q=>tests.includes(q.family)&&topics.includes(q.skill as Skill));
 const q=deck[index]; const active=deck.length>0&&!done;
 const validCount=Number.isInteger(Number(count))&&Number(count)>0&&Number(count)<=pool.length;
 const score=answers.filter(a=>a.correct).length;
 function start() { if(!pool.length || (mode==='round'&&!validCount)) return; setDeck(shuffle(pool).slice(0,mode==='round'?Number(count):pool.length).map(q=>({...q,options:shuffle(q.options)})));setIndex(0);setAnswers([]);setValues(['','']);setSubmitted(false);setDone(false);setError('');setTimeout(()=>heading.current?.focus(),0); }
 function submit(value?:string) { if(submitted)return; const v=value?[value]:values; const numeric=q.skill==='ci'||q.skill==='pvalue'; if(numeric&&(v.slice(0,q.answer.length).some(x=>x.trim()===''||!Number.isFinite(Number(x)))||(q.skill==='pvalue'&&(Number(v[0])<0||Number(v[0])>1))||(q.skill==='ci'&&Number(v[0])>=Number(v[1])))){setError('Enter valid numbers'+(q.skill==='pvalue'?' between 0 and 1.':', with the lower bound smaller than the upper bound.'));return;} const correct=q.answer.every((a,i)=>numeric?Math.abs(Number(v[i])-Number(a))<=0.00015:v[i]===a);setAnswers([...answers,{question:q,correct,response:v.slice(0,q.answer.length).join(', ')}]);setSubmitted(true);setError(''); }
 function next(){if(index+1===deck.length){setDone(true);}else{setIndex(index+1);setSubmitted(false);setValues(['','']);setError('');}setTimeout(()=>heading.current?.focus(),0);}
 function reset(){setDeck([]);setDone(false);setError('');}
 return <main className="quiz-shell">
 <div className="intro"><div><span className="eyebrow">AP STATISTICS / INFERENCE PRACTICE</span><h1>Build your test instincts.</h1><p>Choose your tests. Set your pace. Work through the numbers.</p></div><div className="bank-count"><strong>1,000</strong><span>practice problems</span></div></div>
 {!active&&!done&&<div className="setup-grid"><section className="panel"><div className="section-head"><h2>01 <span>Choose your tests</span></h2><button className="text-button" onClick={()=>setTests(tests.length===9?[]:families.map((_,i)=>i))}>{tests.length===9?'Clear':'Select all'}</button></div><div className="test-grid">{families.map((name,i)=><label className={`check-card ${tests.includes(i)?'selected':''}`} key={name}><input type="checkbox" checked={tests.includes(i)} onChange={()=>setTests(tests.includes(i)?tests.filter(t=>t!==i):[...tests,i])}/><span>{name}{[5,8].includes(i)&&<small>Legacy AP topic</small>}</span><span className="tiny-count">{data.filter(q=>q.family===i).length}</span></label>)}</div><p className="note">Goodness-of-fit and slope inference remain available for older course sequences. <a href="https://apcentral.collegeboard.org/courses/ap-statistics/future-revisions" target="_blank" rel="noreferrer">2026–27 curriculum changes ↗</a></p></section>
 <aside className="panel"><h2>02 <span>Choose your skills</span></h2><div className="skill-list">{Object.entries(skills).map(([id,label])=><label key={id}><input type="checkbox" checked={topics.includes(id as Skill)} onChange={()=>setTopics(topics.includes(id as Skill)?topics.filter(t=>t!==id):[...topics,id as Skill])}/>{label}</label>)}</div><p className="note">Confidence intervals apply to proportions, means, paired differences, and slopes—not chi-square tests.</p><h2>03 <span>Set your pace</span></h2><div className="mode-toggle">{[['round','Fixed round'],['single','Question by question']].map(([id,label])=><button key={id} aria-pressed={mode===id} onClick={()=>setMode(id)}>{label}</button>)}</div>{mode==='round'?<label className="number-label">Number of problems<input type="number" min={1} max={pool.length} value={count} onChange={e=>setCount(e.target.value)}/></label>:<p className="note">Keep going until you choose to finish or exhaust the matching bank. No repeats in a session.</p>}<div className="ready"><strong>{pool.length}</strong> matching problems</div>{!pool.length&&<p role="status">Select at least one compatible test and skill.</p>}{mode==='round'&&pool.length>0&&!validCount&&<p role="status">Choose a whole number from 1 to {pool.length}.</p>}<button className="primary wide" disabled={!pool.length||(mode==='round'&&!validCount)} onClick={start}>Start practicing →</button><p className="note">Calculator encouraged. Feedback after every answer.</p></aside></div>}
 {active&&<section className="panel question-panel"><div className="section-head"><span className="eyebrow">{skills[q.skill as Skill]} · {q.id}</span><span>{score} correct / {answers.length} answered</span></div><progress value={index+(submitted?1:0)} max={deck.length} aria-label="Session progress"/><h2 ref={heading} tabIndex={-1}>Question {index+1}{mode==='round'?` of ${deck.length}`:''}</h2><p className="question-text">{q.prompt}</p>{q.options.length>0?<div className="option-grid">{q.options.map(option=><button key={option} disabled={submitted} className={`option ${submitted&&option===q.answer[0]?'right':''} ${submitted&&option===answers[answers.length-1]?.response&&option!==q.answer[0]?'wrong':''}`} onClick={()=>submit(option)}>{option}</button>)}</div>:<form onSubmit={e=>{e.preventDefault();submit();}}><div className="numeric-row">{q.answer.map((_,i)=><label key={i}>{q.skill==='ci'?(i===0?'Lower bound':'Upper bound'):'P-value'}<input autoComplete="off" inputMode="decimal" value={values[i]} disabled={submitted} onChange={e=>setValues(values.map((v,j)=>i===j?e.target.value:v))}/></label>)}</div><p className="note">Round to four decimal places. Answers within 0.00015 are accepted.</p><button className="primary" disabled={submitted}>Check answer</button></form>}{error&&<p role="alert" className="error">{error}</p>}{submitted&&<div className={`feedback ${answers[answers.length-1].correct?'correct':'incorrect'}`} role="status"><strong>{answers[answers.length-1].correct?'Correct.':'Not quite.'}</strong><p>{q.explanation}</p><button className="primary" onClick={next}>{index+1===deck.length?'See results':'Next question →'}</button></div>}<button className="text-button finish" onClick={()=>setDone(true)}>Finish session & review</button></section>}
 {done&&<section className="panel"><span className="eyebrow">SESSION COMPLETE</span><h2 ref={heading} tabIndex={-1} className="result-title">{score} / {answers.length} correct</h2><p>{answers.length?`${Math.round(score/answers.length*100)}% accuracy. ${deck.length-answers.length} questions left unanswered.`:'No answers submitted yet.'}</p><button className="primary" onClick={reset}>Build another quiz</button><div className="review-list">{answers.map(a=><details key={a.question.id}><summary>{a.correct?'✓':'✕'} {a.question.id} · {families[a.question.family]} · {skills[a.question.skill as Skill]}</summary><p>{a.question.prompt}</p><p><strong>Your answer:</strong> {a.response}</p><p>{a.question.explanation}</p></details>)}</div></section>}
 <footer>Original practice questions · Numerically varied scenarios · No repeats within a session</footer>
 </main>;
}
