"use client";
import {useEffect,useState} from "react";
import {NormalLab} from "./normal-lab";
const modes=['Sampling means','Confidence intervals','Coin convergence','Normal model'] as const;
type Mode=typeof modes[number];
function normal(){return Math.sqrt(-2*Math.log(1-Math.random()))*Math.cos(2*Math.PI*Math.random());}
export function SimulationStudio(){
 const [mode,setMode]=useState<Mode>('Sampling means');const [n,setN]=useState(30);const [running,setRunning]=useState(false);const [values,setValues]=useState<number[]>([]);const [confidence,setConfidence]=useState(95);
 function reset(){setRunning(false);setValues([]);}
 function draw(count=1){setValues(old=>{const added=Array.from({length:count},()=>mode==='Sampling means'?Array.from({length:n},()=>-Math.log(1-Math.random())).reduce((a,b)=>a+b,0)/n:mode==='Confidence intervals'?50+10/Math.sqrt(n)*normal():Math.random()<0.5?1:0);return [...old,...added].slice(0,2000);});}
 useEffect(()=>{if(!running)return;const id=setInterval(()=>{setValues(old=>{if(old.length>=2000)return old;const v=mode==='Sampling means'?Array.from({length:n},()=>-Math.log(1-Math.random())).reduce((a,b)=>a+b,0)/n:mode==='Confidence intervals'?50+10/Math.sqrt(n)*normal():Math.random()<0.5?1:0;return [...old,v];});},100);return()=>clearInterval(id);},[running,mode,n]);
 const z=confidence===90?1.645:confidence===95?1.96:2.576;const margin=z*10/Math.sqrt(n);const covered=values.filter(v=>Math.abs(v-50)<=margin).length;
 const bins=Array.from({length:30},()=>0);values.forEach(v=>{bins[Math.min(29,Math.max(0,Math.floor(v/3*30)))]+=1;});
 const max=Math.max(1,...bins);const cumulative=values.reduce<number[]>((a,v)=>[...a,(a.at(-1)??0)+v],[]);const heads=cumulative.at(-1)??0;const path=cumulative.map((sum,i)=>`${i===0?'M':'L'}${40+660*(i/(Math.max(1,values.length-1)))} ${260-220*sum/(i+1)}`).join(' ');
 return <section className="studio"><div className="studio-tabs" aria-label="Simulation">{modes.map(m=><button key={m} aria-pressed={m===mode} onClick={()=>{setMode(m);reset();}}>{m}</button>)}</div>
 {mode==='Normal model'?<NormalLab/>:<div className="activity-panel"><div className="activity-top"><span className="kicker">Live experiment</span><span>{values.length.toLocaleString()} / 2,000 {mode==='Coin convergence'?'flips':'samples'}</span></div><h2>{mode}</h2><p>{mode==='Sampling means'?'Draw independent samples from a right-skewed Exponential population (μ = 1, σ = 1). Watch the distribution of sample means become more symmetric as n increases.':mode==='Confidence intervals'?'Repeated independent samples from a Normal population with μ = 50 and known σ = 10. Each line is a z interval; orange lines miss the fixed population mean.':'Flip a fair coin repeatedly. The running proportion of heads fluctuates but tends to settle near 0.5. Past results do not change the next flip’s probability.'}</p>
 <div className="sim-controls">{mode!=='Coin convergence'&&<label className="field">Sample size n = {n}<input type="range" min="1" max="100" value={n} onChange={e=>{setN(Number(e.target.value));reset();}}/></label>}{mode==='Confidence intervals'&&<label className="field">Confidence level<select value={confidence} onChange={e=>{setConfidence(Number(e.target.value));reset();}}>{[90,95,99].map(v=><option key={v} value={v}>{v}%</option>)}</select></label>}<button className="button button-accent" disabled={values.length>=2000} onClick={()=>setRunning(!running)}>{running?'Pause':'Animate'}</button><button className="button button-dark" disabled={values.length>=2000} onClick={()=>draw(100)}>Add 100</button><button className="text-button" onClick={reset}>Reset</button></div>
 <svg className="sim-chart" viewBox="0 0 740 310" role="img" aria-label={mode==='Sampling means'?`Histogram of ${values.length} sample means; horizontal axis 0 to 3, vertical axis frequency.`:mode==='Confidence intervals'?`Last 30 confidence intervals; ${covered} of ${values.length} intervals contain the population mean 50.`:`Running heads proportion after ${values.length} flips.`}>
 <line x1="40" x2="710" y1="260" y2="260" stroke="#8b96a6"/>
 {mode==='Sampling means'?<>{bins.map((b,i)=><rect key={i} x={40+i*22} y={260-b/max*210} width="19" height={b/max*210} fill="#ff8a4c"><title>{(i/10).toFixed(1)}–{((i+1)/10).toFixed(1)}: {b} samples{i===29?' (includes overflow above 3)':''}</title></rect>)}<line x1="260" x2="260" y1="30" y2="260" stroke="#101b2d" strokeDasharray="5 5"/>{[0,1,2,3].map(v=><text key={v} x={40+v*220} y="287" textAnchor="middle">{v}</text>)}<text x="270" y="24">μ = 1</text></>:mode==='Confidence intervals'?<><line x1="370" x2="370" y1="10" y2="260" stroke="#101b2d" strokeDasharray="5 5"/>{values.slice(-30).map((v,i)=><g key={values.length-30+i} stroke={Math.abs(v-50)<=margin?'#18745c':'#bf510e'}><line x1={370+(v-margin-50)*6} x2={370+(v+margin-50)*6} y1={12+i*8} y2={12+i*8} strokeWidth="3"/><circle cx={370+(v-50)*6} cy={12+i*8} r="3"/></g>)}{[0,25,50,75,100].map(v=><text key={v} x={70+v*6} y="287" textAnchor="middle">{v}</text>)}</>:<><line x1="40" x2="710" y1="150" y2="150" stroke="#18745c" strokeDasharray="5 5"/><path d={path} fill="none" stroke="#bf510e" strokeWidth="2.5"/><text x="5" y="155">0.5</text><text x="15" y="45">1</text><text x="15" y="265">0</text><text x="40" y="287">1</text><text x="680" y="287">{values.length||1}</text></>}
 {!values.length&&<text x="370" y="120" textAnchor="middle">Press Animate or Add 100 to begin</text>}</svg>
 <div className="sim-results" aria-live="polite">{mode==='Sampling means'?<><strong>Theoretical SE: {(1/Math.sqrt(n)).toFixed(3)}</strong><span>Mean of simulated means: {values.length?(values.reduce((a,b)=>a+b,0)/values.length).toFixed(3):'—'}</span><span>Final bin includes any means ≥ 2.9.</span></>:mode==='Confidence intervals'?<><strong>Captured μ: {covered} / {values.length} ({values.length?(100*covered/values.length).toFixed(1):'0'}%)</strong><span>Margin of error: ±{margin.toFixed(2)} · showing last 30 intervals</span></>:<><strong>Heads proportion: {values.length?(heads/values.length).toFixed(3):'—'}</strong><span>Next-flip probability stays 0.5.</span></>}</div>
 <details className="reflection"><summary>Pause and predict</summary><p>{mode==='Sampling means'?'Quadruple n. The standard error halves, while the center stays at 1. Try n = 1 and n = 100; compare shape and spread.':mode==='Confidence intervals'?'Raise confidence from 90% to 99%. Intervals widen and the long-run capture rate rises. The parameter is fixed; the intervals vary.':'Can ten heads in a row make tails more likely next? No: flips are independent. A long-run proportion approaching 0.5 does not require an immediate balancing streak.'}</p></details>
 </div>}</section>;
}
